apiVersion: v1
kind: Service
metadata:
  name: {{ include "rzc-chart-reezoshop.fullname" . }}
  labels:
    {{- include "rzc-chart-reezoshop.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if (and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP)))}}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "rzc-chart-reezoshop.selectorLabels" . | nindent 4 }}
